CREATE TABLE REGISTER
(

NAME VARCHAR2(20) NOT NULL,
PHONE_NUMBER NUMBER(10) NOT NULL,
EMAIL VARCHAR2(40) NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL,
DEPT_NAME VARCHAR2(20) NOT NULL,
EXPERIENCE NUMBER(38) NOT NULL

);
ALTER TABLE REGISTER MODIFY DEPT_NAME VARCHAR2(55);

ALTER TABLE REGISTER ADD CONSTRAINT email_unique UNIQUE(EMAIL);

ALTER TABLE REGISTER
ADD CONSTRAINT pk_constraint_key PRIMARY KEY(NAME,PHONE_NUMBER,PASSWORD,DEPT_NAME);

SELECT * FROM USER_CONS_COLUMNS where TABLE_NAME='REGISTER';

SELECT * FROM REGISTER;


CREATE TABLE ADMINREGISTARTION
(

ID NUMBER(10) NOT NULL,
ADMIN_ID NUMBER(10) NOT NULL,
ADMIN_NAME VARCHAR2(20) NOT NULL,
EMAIL_ID VARCHAR2(55) NOT NULL,
PHONE_NUMBER NUMBER(10) NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL

);

ALTER TABLE ADMINREGISTRATION ADD CONSTRAINT emailadmin_unique UNIQUE(EMAIL_ID);

ADD CONSTRAINT primarykey_admin PRIMARY KEY(ID,ADMIN_ID,ADMIN_NAME,PHONE_NUMBER,PASSWORD);

SELECT * FROM USER_CONS_COLUMNS where TABLE_NAME='ADMINREGISTRATION';

SELECT * FROM ADMINREGISTRATION;
DESC ADMINREGISTRATION;

CREATE SEQUENCE adminregistration_id_seq
START WITH 1
INCREMENT BY 1;

CREATE TABLE ADMIN
(

ID NUMBER(5) NOT NULL,
ADMIN_ID NUMBER(5) NOT NULL,
ADMIN_NAME VARCHAR2(20) NOT NULL,
VACANCY_DEPT VARCHAR2(55) NOT NULL,
VACANCY_DETAILS VARCHAR2(20) NOT NULL,
JOB_LOCATION VARCHAR2(20) NOT NULL,
COMPANY_NAME VARCHAR2(20) NOT NULL,
PHONE_NO NUMBER(10) NOT NULL

);

ALTER TABLE ADMIN
ADD CONSTRAINT primary_keyconstraint PRIMARY KEY(ID,ADMIN_ID,ADMIN_NAME,VACANCY_DEPT,VACANCY_DETAILS,
JOB_LOCATION,COMPANY_NAME,PHONE_NO);

SELECT * FROM USER_CONS_COLUMNS where TABLE_NAME='ADMIN';

CREATE SEQUENCE admin_idno_seq
STRAT WITH 1
INCREMENT BY 1;

DESC ADMIN;

SELECT * FROM ADMIN;

SELECT * FROM REGISTER;

SELECT * FROM ADMINREGISTRATION;

ALTER TABLE REGISTER ADD CONSTRAINT email_unique UNIQUE(EMAIL);

DESC REGISTER;

ALTER TABLE ADMINREGISTRATION ADD CONSTRAINT emailadmin_unique UNIQUE(EMAIL_ID);

